# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('ns', 'New Stock'), ('ur', 'Usable Return'), ('nr', 'Unusable Return')], default='dkr', help_text='Region', max_length=3)),
                ('city', models.CharField(help_text='Ville', max_length=100)),
                ('flat', models.CharField(blank=True, help_text='Appartement', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Donated amount!')),
                ('method', models.CharField(choices=[('wari', 'Wari'), ('credit', 'Carte de cr\xe9dit'), ('omoney', 'Orange Money')], default='credit', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='donors')),
                ('full_name', models.CharField(help_text='Pr\xe9nom & Nom du Donneur', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Adresse Mail', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text='Num\xe9ro t\xe9l\xe9phone', max_length=100, null=True)),
                ('donor_type', models.CharField(choices=[('anonymous', 'Donneur anonyme'), ('registered', 'Donneur avec compte')], default='registered', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='seekers')),
                ('phone', models.CharField(help_text='Numero telephone', max_length=100)),
                ('description', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sos.Seeker'),
        ),
    ]
