# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='seeker',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='priority',
            field=models.CharField(choices=[('0', 'Urgent'), ('1', 'Normal'), ('2', 'Bas')], default='1', max_length=1),
        ),
    ]
