# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_auto_20180704_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='sos.Seeker'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('dkr', 'Dakar'), ('ths', 'Thies'), ('sl', 'Fatick'), ('kld', 'Kolda'), ('zg', 'Ziguinchor')], default='dkr', help_text='Region', max_length=3),
        ),
    ]
