# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_auto_20180709_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('occasionnel', 'Donneur occasionnel'), ('permanent', 'Donneur Permanent (avec un compte)')], default='registered', max_length=20),
        ),
    ]
