# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_auto_20180712_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='donors'),
        ),
    ]
