# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_auto_20180716_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='target_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
