# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0006_seeker_target_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='seeker',
        ),
        migrations.AddField(
            model_name='seeker',
            name='donations',
            field=models.ManyToManyField(to='sos.Donation'),
        ),
    ]
