# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0007_auto_20180716_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sos.Seeker'),
        ),
    ]
