# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0008_donation_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
