# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0009_auto_20180717_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='google_map',
            field=models.CharField(blank=True, help_text='Adresse google map', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('succes', 'Succes'), ('echec', 'Echec'), ('en attente', 'En attente')], default='en attente', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thies'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('ziguinchor', 'Ziguinchor')], default='dkr', help_text='Region', max_length=3),
        ),
    ]
