# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0010_auto_20180718_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(blank=True, choices=[('succes', 'Succes'), ('echec', 'Echec'), ('en attente', 'En attente')], default='en attente', max_length=30, null=True),
        ),
    ]
