# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0011_auto_20180718_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='photo',
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('anonymous', 'Donneur Anonyme'), ('permanent', 'Donneur Permanent (avec un compte)')], default='registered', max_length=20),
        ),
    ]
