# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sos', '0012_auto_20180725_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='full_name',
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
