# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_auto_20180726_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='patient',
        ),
    ]
