# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-28 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_remove_donation_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donor_type',
        ),
    ]
