# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_auto_20180809_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thies'), ('fatick', 'Fatick'), ('kolda', 'Kolda'), ('ziguinchor', 'Ziguinchor')], default='dkr', help_text='Region', max_length=50),
        ),
    ]
