# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0006_auto_20180809_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='patient',
            field=models.IntegerField(blank=True, help_text='patient unique Id', null=True),
        ),
    ]
